package entidades;
// Generated 15/07/2019 09:12:37 AM by Hibernate Tools 4.3.1



/**
 * MascotaporclienteId generated by hbm2java
 */
public class MascotaporclienteId  implements java.io.Serializable {


     private int clienteIdCliente;
     private int mascotaIdMascota;

    public MascotaporclienteId() {
    }

    public MascotaporclienteId(int clienteIdCliente, int mascotaIdMascota) {
       this.clienteIdCliente = clienteIdCliente;
       this.mascotaIdMascota = mascotaIdMascota;
    }
   
    public int getClienteIdCliente() {
        return this.clienteIdCliente;
    }
    
    public void setClienteIdCliente(int clienteIdCliente) {
        this.clienteIdCliente = clienteIdCliente;
    }
    public int getMascotaIdMascota() {
        return this.mascotaIdMascota;
    }
    
    public void setMascotaIdMascota(int mascotaIdMascota) {
        this.mascotaIdMascota = mascotaIdMascota;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MascotaporclienteId) ) return false;
		 MascotaporclienteId castOther = ( MascotaporclienteId ) other; 
         
		 return (this.getClienteIdCliente()==castOther.getClienteIdCliente())
 && (this.getMascotaIdMascota()==castOther.getMascotaIdMascota());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getClienteIdCliente();
         result = 37 * result + this.getMascotaIdMascota();
         return result;
   }   

    public void getIdCliente(int idCliente) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setIdMascota(int idMascota) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


}


