package entidades;
// Generated 15/07/2019 09:12:37 AM by Hibernate Tools 4.3.1



/**
 * Vacunas generated by hbm2java
 */
public class Vacunas  implements java.io.Serializable {


     private int idVacuna;
     private String tipoVacuna;
     private Integer edad;
     private String precio;

    public Vacunas() {
    }

	
    public Vacunas(int idVacuna) {
        this.idVacuna = idVacuna;
    }
    public Vacunas(int idVacuna, String tipoVacuna, Integer edad, String precio) {
       this.idVacuna = idVacuna;
       this.tipoVacuna = tipoVacuna;
       this.edad = edad;
       this.precio = precio;
    }
   
    public int getIdVacuna() {
        return this.idVacuna;
    }
    
    public void setIdVacuna(int idVacuna) {
        this.idVacuna = idVacuna;
    }
    public String getTipoVacuna() {
        return this.tipoVacuna;
    }
    
    public void setTipoVacuna(String tipoVacuna) {
        this.tipoVacuna = tipoVacuna;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public String getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(String precio) {
        this.precio = precio;
    }




}


